import {MdOutlineMaximize} from 'react-icons/md'

export const isOnline = false

export const REVIEWS: any[] = [
  {
    id: '1',
    firstName: 'Leo',
    date: 1708407370485,
    stars: 3,
    tags: ['Not applicable', 'There are contradictions', 'Unclear'],
    description: 'This Java course is great for students !',
    isOnline: true,
  },
]

export const AVAILABLE_DATA = [
  {
    id: '1',
    name: '1',
    email: '1@gmail.com',
    isChecked: false,
    isOnline: false,
  },
  {
    id: '2',
    name: '2',
    email: '2@gmail.com',
    isChecked: false,
    isOnline: false,
  },
  {
    id: '3',
    name: '3',
    email: '3@gmail.com',
    isChecked: false,
    isOnline: false,
  },
  {
    id: '4',
    name: '4',
    email: '4@gmail.com',
    isChecked: false,
    isOnline: false,
  },
  {
    id: '5',
    name: '5',
    email: '5@gmail.com',
    isChecked: false,
    isOnline: false,
  },
]

export const STUDENT_DATA = [
  {
    id: 1,
    name: 'Leo',
    email: 'mr.alijonov.azizbek@gmail.com',
    points: <MdOutlineMaximize />,
    efficiency: '100%',
    medals: 'Gold',
    retakes: 1,
    assignedThroughProgram: true,
    startDate: '02/09/2024',
    endDate: '02/12/2024',
    finishedDate: '02/14/2024',
    deadline: '02/15/2024',
    isStarted: false,
  },
  {
    id: 2,
    name: 'Leo',
    email: 'mr.alijonov.azizbek@gmail.com',
    points: <MdOutlineMaximize />,
    efficiency: '100%',
    medals: 'Gold',
    retakes: 1,
    assignedThroughProgram: true,
    startDate: '02/09/2024',
    endDate: '02/12/2024',
    finishedDate: '02/14/2024',
    deadline: '02/15/2024',
    isStarted: true,
  },
  {
    id: 3,
    name: 'Leo',
    email: 'mr.alijonov.azizbek@gmail.com',
    points: <MdOutlineMaximize />,
    efficiency: '100%',
    medals: 'Gold',
    retakes: 1,
    assignedThroughProgram: true,
    startDate: '02/09/2024',
    endDate: '02/12/2024',
    finishedDate: '02/14/2024',
    deadline: '02/15/2024',
    isStarted: false,
  },
  {
    id: 4,
    name: 'Leo',
    email: 'mr.alijonov.azizbek@gmail.com',
    points: <MdOutlineMaximize />,
    efficiency: '100%',
    medals: 'Gold',
    retakes: 1,
    assignedThroughProgram: true,
    startDate: '02/09/2024',
    endDate: '02/12/2024',
    finishedDate: '02/14/2024',
    deadline: '02/15/2024',
    isStarted: true,
  },
]
